apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-to-image-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-to-image-api
  template:
    metadata:
      labels:
        app: html-to-image-api
    spec:
      containers:
        - name: html-to-image-api
          image: eshows/html-to-image-api:latestv1
          ports:
            - containerPort: 3003
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          env:
            - name: PORT
              value: "3003"
            - name: teste
              value: "https:/picdhaosssssssssss"
      imagePullSecrets:
        - name: my-dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: html-to-image-api-service
spec:
  selector:
    app: html-to-image-api
  ports:
    - port: 3003
      targetPort: 3003
  type: ClusterIP
